import openai
import os

from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv())

openai.api_key  = os.getenv('OPENAI_API_KEY')

def get_completion(prompt, model="gpt-3.5-turbo"):
    """
    Generate a chat message completion using OpenAI's GPT-3 model.

    Args:
        prompt (str): The user's message prompt to be completed.
        model (str): The name of the GPT-3 model to use (default: "gpt-3.5-turbo").

    Returns:
        str: The completed message generated by the model.
    """
    messages = [{"role": "user", "content": prompt}]
    response = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=0, # this is the degree of randomness of the model's output
    )
    return response.choices[0].message["content"]